# Generated by Django 3.2.11 on 2022-01-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_testtable_testjsonfeild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='TestjsonFeild',
            field=models.JSONField(default=list),
        ),
    ]
