# Generated by Django 3.2.11 on 2022-01-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='ApprovedOn',
            field=models.DateField(),
        ),
    ]
