# Generated by Django 3.2.11 on 2022-01-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0007_rename_submission_submissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submissions',
            new_name='Submission',
        ),
    ]
