# Generated by Django 3.2.11 on 2022-01-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0008_rename_submissions_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='SubmissionId',
            new_name='SubmissionID',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('AttachmentID', models.AutoField(primary_key=True, serialize=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('URL', models.CharField(max_length=500)),
                ('AlterTitle', models.CharField(default='alter', max_length=500)),
                ('SubmissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIs.submission')),
            ],
        ),
    ]
