# Generated by Django 3.2.11 on 2022-01-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0010_auto_20220109_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
