# Generated by Django 3.2.11 on 2022-01-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0012_auto_20220111_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ApprovedBy',
        ),
    ]
