# Generated by Django 3.2.11 on 2022-01-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0013_remove_post_approvedby'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
